pipeline {
	agent any
	options {
		skipsStageAfterUnstable()
	}
	stages {
		stage('Build') {
			stpes {
				sh 'make'
			}
		}
		stage('Test') {
			steps {
				sh 'make check'
				junit 'reports/**/*.xml'
			}
		}
		stage('Deploy') {
			steps {
				sh 'make publish'
			}
		}
	}
}